title: Java OOP - Campus Mölndal
description: "En online bok för att lära och repetera OOP-koncept i Java"
theme: just-the-docs
baseurl: "/javaoop"
url: "https://CampusMolndalEducation.github.io"
theme: "just-the-docs"
remote_theme: "just-the-docs/just-the-docs"

# Timezone
timezone: "Europe/Stockholm"

# Default encoding
encoding: "utf-8"

# Aux links
aux_links:
  Campus Mölndal YH: https://campus.molndal.se/campus-molndal/utbildningar/yrkeshogskola/it-utbildningar.html

aux_links_new_tab: true
